version: 0.0
os: linux
files:
  - source: / # The root of your build artifact
    destination: /var/www/html/my-app # Where to deploy on the EC2 instance
permissions:
  - object: /var/www/html/my-app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: ec2-user
