# Generated by Django 5.2 on 2025-05-10 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_product_category_remove_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, to='app.category'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='product',
            name='Sub_Category',
            field=models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, to='app.sub_category'),
            preserve_default='False',
        ),
    ]
