# Generated by Django 5.2 on 2025-05-15 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_contactformsubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactformsubmission',
            options={'ordering': ['-submission_date'], 'verbose_name_plural': 'Contact Form Submissions'},
        ),
    ]
