# Generated by Django 5.2 on 2025-05-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_contactformsubmission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactformsubmission',
            options={'ordering': ['-submission_date'], 'verbose_name_plural': 'Contact Form data'},
        ),
    ]
